# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture_code', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0, null=True)),
                ('consumer_count', models.IntegerField(default=0, null=True)),
                ('consumption_ammount', models.IntegerField(default=0, null=True)),
                ('guest_count_hotel', models.IntegerField(default=0, null=True)),
                ('guest_count_ryokan', models.IntegerField(default=0, null=True)),
                ('guest_count_condominium', models.IntegerField(default=0, null=True)),
                ('guest_count_dorm', models.IntegerField(default=0, null=True)),
                ('guest_count_house', models.IntegerField(default=0, null=True)),
                ('guest_count_youthhostel', models.IntegerField(default=0, null=True)),
                ('guest_count_other', models.IntegerField(default=0, null=True)),
                ('website_count', models.IntegerField(default=0, null=True)),
                ('total_floor_area', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_code', models.IntegerField(default=0)),
                ('city_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Company_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('ceo', models.CharField(max_length=30)),
                ('gmap', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture_code', models.IntegerField(default=0)),
                ('city_code', models.IntegerField(default=0, null=True)),
                ('year', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('rent', models.IntegerField(default=0)),
                ('restroom_facility_cost', models.IntegerField(default=0)),
                ('bathroom_facility_cost', models.IntegerField(default=0)),
                ('kitchen_facility_cost', models.IntegerField(default=0)),
                ('reform_fee', models.IntegerField(default=0)),
                ('repainting_fee', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ForeignGuestCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture_code', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('guest_count', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='GuestNationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture_code', models.IntegerField(default=0)),
                ('answer_count', models.IntegerField(default=0)),
                ('visit_duration', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Member_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=60, null=True)),
                ('position', models.CharField(max_length=15, null=True)),
                ('member_flg', models.IntegerField(default=0)),
                ('twitter_url', models.CharField(max_length=100, null=True)),
                ('facebook_url', models.CharField(max_length=100, null=True)),
                ('linkedin_url', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberFlg_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_flg', models.IntegerField(default=0)),
                ('role', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality_code', models.IntegerField(default=0)),
                ('nationality_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture_code', models.IntegerField(default=0)),
                ('prefecture_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PriceofLand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture_code', models.IntegerField(default=0)),
                ('city_code', models.IntegerField(default=0, null=True)),
                ('properties_count', models.IntegerField(default=0, null=True)),
                ('avg_price', models.IntegerField(default=0, null=True)),
                ('upper_price', models.IntegerField(default=0, null=True)),
                ('lower_price', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture_code', models.IntegerField(default=0, null=True)),
                ('city_code', models.IntegerField(default=0, null=True)),
                ('total_listing_rank', models.IntegerField(default=0)),
                ('average_price_rank', models.IntegerField(default=0)),
                ('monthly_sales_rank', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_region_city', to='ac_site.City')),
                ('prefecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_region_prefecture', to='ac_site.Prefecture')),
            ],
        ),
        migrations.CreateModel(
            name='RegionSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture_code', models.IntegerField(default=0, null=True)),
                ('city_code', models.IntegerField(default=0, null=True)),
                ('year', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('total_listing', models.IntegerField(default=0, null=True)),
                ('publish_count', models.IntegerField(default=0, null=True)),
                ('suspend_count', models.IntegerField(default=0, null=True)),
                ('reviewed_count', models.IntegerField(default=0, null=True)),
                ('non_reviewed_count', models.IntegerField(default=0, null=True)),
                ('average_price', models.IntegerField(default=0, null=True)),
                ('monthly_sales', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_regionsummary', to='ac_site.Region')),
            ],
        ),
        migrations.CreateModel(
            name='SummaryArticleBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_prefecture_code', models.IntegerField(default=0)),
                ('link_city_code', models.IntegerField(default=0, null=True)),
                ('article_type', models.CharField(max_length=10, null=True)),
                ('listing_count', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('region_summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_breakdown', to='ac_site.RegionSummary')),
            ],
        ),
        migrations.CreateModel(
            name='SummaryCapacityBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_prefecture_code', models.IntegerField(default=0)),
                ('link_city_code', models.IntegerField(default=0, null=True)),
                ('capacity_type', models.CharField(max_length=10, null=True)),
                ('listing_count', models.IntegerField(default=0, null=True)),
                ('average_sales', models.IntegerField(default=0, null=True)),
                ('average_rental_fee', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('region_summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capacity_breakdown', to='ac_site.RegionSummary')),
            ],
        ),
        migrations.CreateModel(
            name='SummaryLanguageBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_prefecture_code', models.IntegerField(default=0)),
                ('link_city_code', models.IntegerField(default=0, null=True)),
                ('language_type', models.CharField(max_length=10, null=True)),
                ('listing_count', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('region_summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language_breakdown', to='ac_site.RegionSummary')),
            ],
        ),
        migrations.CreateModel(
            name='SummarySizeBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_prefecture_code', models.IntegerField(default=0)),
                ('link_city_code', models.IntegerField(default=0, null=True)),
                ('room_size', models.CharField(max_length=10, null=True)),
                ('listing_count', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('region_summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_breakdown', to='ac_site.RegionSummary')),
            ],
        ),
        migrations.CreateModel(
            name='TourResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture_code', models.IntegerField(default=0)),
                ('city_code', models.IntegerField(default=0, null=True)),
                ('scr_type1', models.CharField(max_length=20, null=True)),
                ('scr_type2', models.CharField(max_length=20, null=True)),
                ('scr_name', models.CharField(max_length=50, null=True)),
                ('scr_rank', models.CharField(max_length=5, null=True)),
                ('scr_score', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_tourresource', to='ac_site.Region')),
            ],
        ),
        migrations.AddField(
            model_name='ranking',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_ranking', to='ac_site.Region'),
        ),
        migrations.AddField(
            model_name='priceofland',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_priceofland', to='ac_site.Region'),
        ),
        migrations.AddField(
            model_name='guestnationality',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_guestnationality_nationality', to='ac_site.Nationality'),
        ),
        migrations.AddField(
            model_name='guestnationality',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_guestnationality', to='ac_site.Region'),
        ),
        migrations.AddField(
            model_name='foreignguestcount',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_foreignguestcount', to='ac_site.Region'),
        ),
        migrations.AddField(
            model_name='cost',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_cost', to='ac_site.Region'),
        ),
        migrations.AddField(
            model_name='annualsummary',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_annualsummary', to='ac_site.Region'),
        ),
    ]
