# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0003_auto_20170920_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='air_table',
            name='rgst_trend',
        ),
        migrations.RemoveField(
            model_name='air_table',
            name='suspnd_trend',
        ),
        migrations.RemoveField(
            model_name='air_table',
            name='suspnd_trend_IX',
        ),
        migrations.RemoveField(
            model_name='air_table',
            name='suspnd_trend_VIII',
        ),
        migrations.RemoveField(
            model_name='air_table',
            name='suspnd_trend_X',
        ),
        migrations.RemoveField(
            model_name='air_table',
            name='suspnd_trend_XI',
        ),
        migrations.RemoveField(
            model_name='air_table',
            name='suspnd_trend_XII',
        ),
    ]
