# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 11:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0011_auto_20170922_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingtrend',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 11, 20, 59, 324700)),
        ),
        migrations.AlterField(
            model_name='summaryarticlebreakdown',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 11, 20, 59, 323264)),
        ),
        migrations.AlterField(
            model_name='summarysizebreakdown',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 11, 20, 59, 322606)),
        ),
    ]
