# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 12:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0020_auto_20170922_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignGuestM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_foreign_month_id', models.IntegerField(default=0)),
                ('prefecture_id', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('number_of_guest', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='listingtrend',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 12, 22, 57, 524893)),
        ),
        migrations.AlterField(
            model_name='summaryarticlebreakdown',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 12, 22, 57, 523483)),
        ),
        migrations.AlterField(
            model_name='summarysizebreakdown',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 12, 22, 57, 522864)),
        ),
    ]
