# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 12:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0022_auto_20170922_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prefecture',
            old_name='prefectur_id',
            new_name='prefecture_id',
        ),
        migrations.AlterField(
            model_name='listingtrend',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 12, 33, 5, 436194)),
        ),
        migrations.AlterField(
            model_name='summaryarticlebreakdown',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 12, 33, 5, 434650)),
        ),
        migrations.AlterField(
            model_name='summarysizebreakdown',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 12, 33, 5, 434011)),
        ),
    ]
