# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0024_auto_20170922_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionsummary',
            name='city_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='regionsummary',
            name='prefecture_id',
            field=models.IntegerField(default=0),
        ),
    ]
