# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0027_auto_20170923_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_id', models.IntegerField(default=0)),
                ('prefecture_id', models.IntegerField(default=0)),
                ('city_id', models.IntegerField(default=0, null=True)),
                ('total_listing', models.IntegerField(default=0, null=True)),
                ('publish_count', models.IntegerField(default=0, null=True)),
                ('suspend_count', models.IntegerField(default=0, null=True)),
                ('reviewed_count', models.IntegerField(default=0, null=True)),
                ('non_reviewed_count', models.IntegerField(default=0, null=True)),
                ('average_price', models.IntegerField(default=0, null=True)),
                ('monthly_sales', models.IntegerField(default=0, null=True)),
                ('region_summary_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SummaryLanguageBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_summary_id', models.IntegerField(default=0)),
                ('dutch', models.IntegerField(default=0, null=True)),
                ('germany', models.IntegerField(default=0, null=True)),
                ('thai', models.IntegerField(default=0, null=True)),
                ('italian', models.IntegerField(default=0, null=True)),
                ('french', models.IntegerField(default=0, null=True)),
                ('korean', models.IntegerField(default=0, null=True)),
                ('chinese', models.IntegerField(default=0, null=True)),
                ('spanish', models.IntegerField(default=0, null=True)),
                ('english', models.IntegerField(default=0, null=True)),
                ('japanese', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
