# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0028_regionsummary_summarylanguagebreakdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summarylanguagebreakdown',
            name='chinese',
        ),
        migrations.RemoveField(
            model_name='summarylanguagebreakdown',
            name='dutch',
        ),
        migrations.RemoveField(
            model_name='summarylanguagebreakdown',
            name='english',
        ),
        migrations.RemoveField(
            model_name='summarylanguagebreakdown',
            name='french',
        ),
        migrations.RemoveField(
            model_name='summarylanguagebreakdown',
            name='germany',
        ),
        migrations.RemoveField(
            model_name='summarylanguagebreakdown',
            name='italian',
        ),
        migrations.RemoveField(
            model_name='summarylanguagebreakdown',
            name='japanese',
        ),
        migrations.RemoveField(
            model_name='summarylanguagebreakdown',
            name='korean',
        ),
        migrations.RemoveField(
            model_name='summarylanguagebreakdown',
            name='spanish',
        ),
        migrations.RemoveField(
            model_name='summarylanguagebreakdown',
            name='thai',
        ),
    ]
