# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0029_auto_20170924_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summarysizebreakdown',
            name='monthly_sales',
        ),
        migrations.AddField(
            model_name='summarylanguagebreakdown',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='summarylanguagebreakdown',
            name='language_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='summarylanguagebreakdown',
            name='listing_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
