# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0030_auto_20170924_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryCapacityBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_summary_id', models.IntegerField(default=0)),
                ('capacity_type', models.CharField(max_length=10, null=True)),
                ('listing_count', models.IntegerField(default=0, null=True)),
                ('average_salses', models.IntegerField(default=0, null=True)),
                ('average_rental_fee', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
