# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0033_auto_20170925_0807'),
    ]

    operations = [
#        migrations.AlterField(
#            model_name='consumption',
#            name='prefecture',
#            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_site.Prefecture'),
#        ),
#        migrations.AlterField(
#            model_name='foreignguest',
#            name='prefecture',
#            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_site.Prefecture'),
#        ),
#        migrations.AlterField(
#            model_name='foreignguestm',
#            name='prefecture',
#            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_site.Prefecture'),
#        ),
#        migrations.AlterField(
#            model_name='hoteltype',
#            name='prefecture_id',
#            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_site.Prefecture'),
#        ),
#        migrations.AlterField(
#            model_name='prefecture',
#            name='prefecture_id',
#            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_site.Region'),
#        ),
#        migrations.AlterField(
#            model_name='priceofland',
#            name='prefecture_id',
#            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_site.Prefecture'),
#        ),
#        migrations.AlterField(
#            model_name='regionsummary',
#            name='prefecture_id',
#            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_site.Prefecture'),
#        ),
#        migrations.AlterField(
#            model_name='summaryarticlebreakdown',
#            name='region_summary_id',
#            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_site.RegionSummary'),
#        ),
#        migrations.AlterField(
#            model_name='summarycapacitybreakdown',
#            name='region_summary_id',
#            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_site.RegionSummary'),
#        ),
#        migrations.AlterField(
#            model_name='summarylanguagebreakdown',
#            name='region_summary_id',
#            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_site.RegionSummary'),
#        ),
#        migrations.AlterField(
#            model_name='summarysizebreakdown',
#            name='region_summary_id',
#            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_site.RegionSummary'),
#        ),
#        migrations.AlterField(
#            model_name='tourresource',
#            name='prefecture_id',
#            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_site.Prefecture'),
#        ),
#        migrations.AlterField(
#            model_name='website',
#            name='prefecture_id',
#            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_site.Prefecture'),
#        ),
    ]
