# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0037_auto_20170926_1653'),
    ]

    operations = [
#        migrations.RenameField(
#            model_name='hoteltype',
#            old_name='prefecture_id',
#            new_name='prefecture',
#        ),
    ]
