# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0041_consumption'),
    ]

    operations = [
#        migrations.DeleteModel(
#            name='Consumption',
#        ),
    ]
