# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0045_remove_consumption_prefecture_id'),
    ]

    operations = [
#        migrations.AddField(
#            model_name='consumption',
#            name='prefecture',
#            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ac_site.Prefecture'),
#        ),
    ]
