# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0049_auto_20170926_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumption',
            name='prefecture',
        ),
    ]
