# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0054_auto_20170926_2049'),
    ]

    operations = [
#        migrations.RenameField(
#            model_name='city',
#            old_name='city_id',
#            new_name='city_id_city',
#        ),
#        migrations.RenameField(
#            model_name='foreignguest',
#            old_name='prefecture_id',
#            new_name='prefecture_id_frg',
#        ),
#        migrations.RenameField(
#            model_name='foreignguestm',
#            old_name='prefecture_id',
#            new_name='prefecture_id_frgm',
#        ),
#        migrations.RenameField(
#            model_name='hoteltype',
#            old_name='prefecture_id',
#            new_name='prefecture_id_htl',
#        ),
#        migrations.RenameField(
#            model_name='prefecture',
#            old_name='prefecture_id',
#            new_name='prefecture_id_pref',
#        ),
#        migrations.RenameField(
#            model_name='priceofland',
#            old_name='city_id',
#            new_name='city_id_pol',
#        ),
#        migrations.RenameField(
#            model_name='priceofland',
#            old_name='prefecture_id',
#            new_name='prefecture_id_pol',
#        ),
#        migrations.RenameField(
#            model_name='regionsummary',
#            old_name='city_id',
#            new_name='city_id_rgs',
#        ),
#        migrations.RenameField(
#            model_name='regionsummary',
#            old_name='prefecture_id',
#            new_name='prefecture_id_rgs',
#        ),
#        migrations.RenameField(
#            model_name='summaryarticlebreakdown',
#            old_name='region_summary_id',
#            new_name='region_summary_id_artcl',
#        ),
#        migrations.RenameField(
#            model_name='summarycapacitybreakdown',
#            old_name='region_summary_id',
#            new_name='region_summary_id_cap',
#        ),
#        migrations.RenameField(
#            model_name='summarylanguagebreakdown',
#            old_name='region_summary_id',
#            new_name='region_summary_id_lang',
#        ),
#        migrations.RenameField(
#            model_name='summarysizebreakdown',
#            old_name='region_summary_id',
#            new_name='region_summary_id_size',
#        ),
#        migrations.RenameField(
#            model_name='tourresource',
#            old_name='city_id',
#            new_name='city_id_scr',
#        ),
#        migrations.RenameField(
#            model_name='tourresource',
#            old_name='prefecture_id',
#            new_name='prefecture_id_scr',
#        ),
#        migrations.RenameField(
#            model_name='website',
#            old_name='prefecture_id',
#            new_name='prefecture_id_web',
#        ),
        migrations.AddField(
            model_name='consumption',
            name='prefecture_id_csm',
            field=models.ForeignKey(blank=True, db_column=b'prefecture_id_csm', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefecture_id_csm', to='ac_site.Region', to_field=b'prefecture_id'),
        ),
#        migrations.AlterField(
#            model_name='region',
#            name='city_id',
#            field=models.IntegerField(default=0, unique=True),
#        ),
#        migrations.AlterField(
#            model_name='region',
#            name='prefecture_id',
#            field=models.IntegerField(default=0, unique=True),
#        ),
        migrations.AlterField(
            model_name='regionsummary',
            name='region_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
