# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0055_auto_20170926_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='prefecture_id_csm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ac_site.Region', to_field=b'prefecture_id'),
        ),
    ]
