# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0056_auto_20170927_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumption',
            name='prefecture_id_csm',
        ),
    ]
