# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0060_auto_20170927_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hoteltype',
            old_name='prefecture_htl',
            new_name='prefecture_id_htl',
        ),
    ]
