# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0061_auto_20170927_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prefecture',
            name='prefecture_id_pref',
        ),
        migrations.DeleteModel(
            name='Prefecture',
        ),
    ]
