# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0062_auto_20170927_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture', models.CharField(max_length=10)),
                ('prefecture_id_pref', models.ForeignKey(blank=True, db_column=b'prefecture_id_pref', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefecture_id_pref', to='ac_site.Region', to_field=b'prefecture_id')),
            ],
        ),
    ]
