# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0069_auto_20170927_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='prefecture_id',
            field=models.OneToOneField(blank=True, db_column=b'prefecture_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefecture_id', to='ac_site.Prefecture', to_field=b'prefecture_id_pref'),
        ),
    ]
