# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0070_auto_20170927_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='prefecture_id_csm',
            field=models.ForeignKey(blank=True, db_column=b'prefecture_id_csm', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefecture_id_csm', to='ac_site.Prefecture', to_field=b'prefecture_id_pref'),
        ),
        migrations.AlterField(
            model_name='foreignguest',
            name='prefecture_id_frg',
            field=models.ForeignKey(blank=True, db_column=b'prefecture_id_frg', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefecture_id_frg', to='ac_site.Prefecture', to_field=b'prefecture_id_pref'),
        ),
        migrations.AlterField(
            model_name='foreignguestm',
            name='prefecture_id_frgm',
            field=models.ForeignKey(blank=True, db_column=b'prefecture_id_frgm', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefecture_id_frgm', to='ac_site.Prefecture', to_field=b'prefecture_id_pref'),
        ),
        migrations.AlterField(
            model_name='hoteltype',
            name='prefecture_id_htl',
            field=models.ForeignKey(blank=True, db_column=b'prefecture_id_htl', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefecture_id_htl', to='ac_site.Prefecture', to_field=b'prefecture_id_pref'),
        ),
        migrations.AlterField(
            model_name='priceofland',
            name='prefecture_id_pol',
            field=models.ForeignKey(blank=True, db_column=b'prefecture_id_pol', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefecture_id_pol', to='ac_site.Prefecture', to_field=b'prefecture_id_pref'),
        ),
        migrations.AlterField(
            model_name='regionsummary',
            name='prefecture_id_rgs',
            field=models.ForeignKey(blank=True, db_column=b'prefecture_id_rgs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefecture_id_rgs', to='ac_site.Prefecture', to_field=b'prefecture_id_pref'),
        ),
        migrations.AlterField(
            model_name='tourresource',
            name='prefecture_id_scr',
            field=models.ForeignKey(blank=True, db_column=b'prefecture_id_scr', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefecture_id_scr', to='ac_site.Prefecture', to_field=b'prefecture_id_pref'),
        ),
        migrations.AlterField(
            model_name='website',
            name='prefecture_id_web',
            field=models.ForeignKey(blank=True, db_column=b'prefecture_id_web', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefecture_id_web', to='ac_site.Prefecture', to_field=b'prefecture_id_pref'),
        ),
    ]
