# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0072_auto_20170928_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prefecture',
            old_name='pref_id_cosumption',
            new_name='pref_id_consumption',
        ),
    ]
