# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0074_auto_20170928_1540'),
    ]

    operations = [
#        migrations.RenameField(
#            model_name='summaryarticlebreakdown',
#            old_name='region_summary',
#            new_name='region_summary_id_artcl',
#        ),
#        migrations.RenameField(
#            model_name='summarycapacitybreakdown',
#            old_name='region_summary',
#            new_name='region_summary_id_cap',
#        ),
#        migrations.RenameField(
#            model_name='summarylanguagebreakdown',
#            old_name='region_summary',
#            new_name='region_summary_id_lang',
#        ),
#        migrations.RenameField(
#            model_name='summarysizebreakdown',
#            old_name='region_summary',
#            new_name='region_summary_id_size',
#        ),
    ]
