# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0077_auto_20170928_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='prefecture_id_csm',
            field=models.OneToOneField(blank=True, db_column=b'prefecture_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_consumption', to='ac_site.Prefecture', to_field=b'prefecture_id_pref'),
        ),
        migrations.AlterField(
            model_name='foreignguest',
            name='prefecture_id_frg',
            field=models.ForeignKey(blank=True, db_column=b'prefecture_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_foreignguest', to='ac_site.Prefecture', to_field=b'prefecture_id_pref'),
        ),
        migrations.AlterField(
            model_name='foreignguestm',
            name='prefecture_id_frgm',
            field=models.ForeignKey(blank=True, db_column=b'prefecture_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_foreignguestm', to='ac_site.Prefecture', to_field=b'prefecture_id_pref'),
        ),
        migrations.AlterField(
            model_name='hoteltype',
            name='prefecture_id_htl',
            field=models.OneToOneField(blank=True, db_column=b'prefecture_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_hoteltype', to='ac_site.Prefecture', to_field=b'prefecture_id_pref'),
        ),
        migrations.AlterField(
            model_name='prefecture',
            name='pref_id_consumption',
            field=models.ForeignKey(blank=True, db_column=b'consumption_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_prefecture_csm', to='ac_site.Consumption', to_field=b'prefecture_id_csm'),
        ),
        migrations.AlterField(
            model_name='prefecture',
            name='pref_id_hoteltype',
            field=models.ForeignKey(blank=True, db_column=b'hoteltype_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_prefecture_hotel', to='ac_site.HotelType', to_field=b'prefecture_id_htl'),
        ),
        migrations.AlterField(
            model_name='prefecture',
            name='pref_id_website',
            field=models.ForeignKey(blank=True, db_column=b'website_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_prefecture_web', to='ac_site.WebSite', to_field=b'prefecture_id_web'),
        ),
        migrations.AlterField(
            model_name='priceofland',
            name='prefecture_id_pol',
            field=models.ForeignKey(blank=True, db_column=b'prefecture_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_priceofland', to='ac_site.Prefecture', to_field=b'prefecture_id_pref'),
        ),
        migrations.AlterField(
            model_name='region',
            name='prefecture_id',
            field=models.OneToOneField(blank=True, db_column=b'prefecture_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_region', to='ac_site.Prefecture', to_field=b'prefecture_id_pref'),
        ),
        migrations.AlterField(
            model_name='regionsummary',
            name='prefecture_id_rgs',
            field=models.ForeignKey(blank=True, db_column=b'prefecture_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_regionsummary', to='ac_site.Prefecture', to_field=b'prefecture_id_pref'),
        ),
        migrations.AlterField(
            model_name='tourresource',
            name='prefecture_id_scr',
            field=models.ForeignKey(blank=True, db_column=b'prefecture_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_tourresource', to='ac_site.Prefecture', to_field=b'prefecture_id_pref'),
        ),
        migrations.AlterField(
            model_name='website',
            name='prefecture_id_web',
            field=models.OneToOneField(blank=True, db_column=b'prefecture_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_website', to='ac_site.Prefecture', to_field=b'prefecture_id_pref'),
        ),
    ]
