# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0086_auto_20170929_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionsummary',
            name='region',
        ),
        migrations.RemoveField(
            model_name='summaryarticlebreakdown',
            name='region_summary',
        ),
        migrations.RemoveField(
            model_name='summarycapacitybreakdown',
            name='region_summary',
        ),
        migrations.RemoveField(
            model_name='summarylanguagebreakdown',
            name='region_summary',
        ),
        migrations.RemoveField(
            model_name='summarysizebreakdown',
            name='region_summary',
        ),
        migrations.DeleteModel(
            name='RegionSummary',
        ),
        migrations.DeleteModel(
            name='SummaryArticleBreakdown',
        ),
        migrations.DeleteModel(
            name='SummaryCapacityBreakdown',
        ),
        migrations.DeleteModel(
            name='SummaryLanguageBreakdown',
        ),
        migrations.DeleteModel(
            name='SummarySizeBreakdown',
        ),
    ]
