# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0087_auto_20170930_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture_code', models.IntegerField(default=0, null=True)),
                ('city_code', models.IntegerField(default=0, null=True)),
                ('year', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('total_listing', models.IntegerField(default=0, null=True)),
                ('publish_count', models.IntegerField(default=0, null=True)),
                ('suspend_count', models.IntegerField(default=0, null=True)),
                ('reviewed_count', models.IntegerField(default=0, null=True)),
                ('non_reviewed_count', models.IntegerField(default=0, null=True)),
                ('average_price', models.IntegerField(default=0, null=True)),
                ('monthly_sales', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_regionsummary', to='ac_site.Region')),
            ],
        ),
        migrations.CreateModel(
            name='SummaryArticleBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_prefecture_code', models.IntegerField(default=0)),
                ('link_city_code', models.IntegerField(default=0, null=True)),
                ('article_type', models.CharField(max_length=10, null=True)),
                ('listing_count', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('region_summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_breakdown', to='ac_site.RegionSummary')),
            ],
        ),
        migrations.CreateModel(
            name='SummaryCapacityBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_prefecture_code', models.IntegerField(default=0)),
                ('link_city_code', models.IntegerField(default=0, null=True)),
                ('capacity_type', models.CharField(max_length=10, null=True)),
                ('listing_count', models.IntegerField(default=0, null=True)),
                ('average_sales', models.IntegerField(default=0, null=True)),
                ('average_rental_fee', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('region_summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capacity_breakdown', to='ac_site.RegionSummary')),
            ],
        ),
        migrations.CreateModel(
            name='SummaryLanguageBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_prefecture_code', models.IntegerField(default=0)),
                ('link_city_code', models.IntegerField(default=0, null=True)),
                ('language_type', models.CharField(max_length=10, null=True)),
                ('listing_count', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('region_summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language_breakdown', to='ac_site.RegionSummary')),
            ],
        ),
        migrations.CreateModel(
            name='SummarySizeBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_prefecture_code', models.IntegerField(default=0)),
                ('link_city_code', models.IntegerField(default=0, null=True)),
                ('room_size', models.CharField(max_length=10, null=True)),
                ('listing_count', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('region_summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_breakdown', to='ac_site.RegionSummary')),
            ],
        ),
    ]
