# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0091_auto_20171001_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualsummary',
            name='region',
        ),
        migrations.RemoveField(
            model_name='city',
            name='region',
        ),
        migrations.RemoveField(
            model_name='foreignguestcount',
            name='region',
        ),
        migrations.RemoveField(
            model_name='prefecture',
            name='region',
        ),
        migrations.RemoveField(
            model_name='regionsummary',
            name='region',
        ),
    ]
