# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('ceo', models.CharField(max_length=30)),
                ('gmap', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Member_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=60)),
                ('position', models.CharField(max_length=15)),
                ('member_flg', models.IntegerField(default=0)),
                ('twitter_url', models.CharField(max_length=100)),
                ('facebook_url', models.CharField(max_length=100)),
                ('linkedin_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MemberFlg_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_flg', models.IntegerField(default=0)),
                ('role', models.CharField(max_length=60)),
            ],
        ),
    ]
