# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0005_auto_20170922_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumption',
            old_name='num_of_answer',
            new_name='num_of_answers',
        ),
    ]
