# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 10:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0008_auto_20170922_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingtrend',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 10, 59, 56, 691352)),
        ),
        migrations.AlterField(
            model_name='summaryarticlebreakdown',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 10, 59, 56, 689956)),
        ),
        migrations.AlterField(
            model_name='summarysizebreakdown',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 10, 59, 56, 689341)),
        ),
    ]
