# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 11:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0013_auto_20170922_2024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Consumption',
        ),
        migrations.DeleteModel(
            name='ForeignGuest',
        ),
        migrations.DeleteModel(
            name='ForeignGuestM',
        ),
        migrations.DeleteModel(
            name='HotelType',
        ),
        migrations.DeleteModel(
            name='PriceofLand',
        ),
        migrations.DeleteModel(
            name='TourResource',
        ),
        migrations.DeleteModel(
            name='WebSite',
        ),
        migrations.AlterField(
            model_name='listingtrend',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 11, 28, 25, 12696)),
        ),
        migrations.AlterField(
            model_name='summaryarticlebreakdown',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 11, 28, 25, 11077)),
        ),
        migrations.AlterField(
            model_name='summarysizebreakdown',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 11, 28, 25, 10381)),
        ),
    ]
