# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 12:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0018_auto_20170922_2055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForeignGuest',
        ),
        migrations.DeleteModel(
            name='ForeignGuestM',
        ),
        migrations.AlterField(
            model_name='listingtrend',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 12, 4, 30, 795092)),
        ),
        migrations.AlterField(
            model_name='summaryarticlebreakdown',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 12, 4, 30, 793681)),
        ),
        migrations.AlterField(
            model_name='summarysizebreakdown',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 12, 4, 30, 793063)),
        ),
    ]
