# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 12:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0019_auto_20170922_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignGuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_foreign_id', models.IntegerField(default=0)),
                ('prefecture_id', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('number_of_guest', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='consumption',
            name='consumption',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='num_of_answers',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hoteltype',
            name='condominium',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hoteltype',
            name='dorm',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hoteltype',
            name='hotel',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hoteltype',
            name='house',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hoteltype',
            name='other',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hoteltype',
            name='ryokan',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hoteltype',
            name='youth_hostel',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='listingtrend',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 12, 20, 53, 627427)),
        ),
        migrations.AlterField(
            model_name='priceofland',
            name='average_price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='priceofland',
            name='lower_price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='priceofland',
            name='properties',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='priceofland',
            name='upper_price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='summaryarticlebreakdown',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 12, 20, 53, 625483)),
        ),
        migrations.AlterField(
            model_name='summarysizebreakdown',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 12, 20, 53, 624854)),
        ),
        migrations.AlterField(
            model_name='tourresource',
            name='scr_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tourresource',
            name='scr_rank',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='tourresource',
            name='scr_score',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tourresource',
            name='scr_type1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tourresource',
            name='scr_type2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='website',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
