# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 12:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0021_auto_20170922_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prefecture',
            old_name='prefecture_id',
            new_name='prefectur_id',
        ),
        migrations.AlterField(
            model_name='listingtrend',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 12, 30, 21, 439870)),
        ),
        migrations.AlterField(
            model_name='summaryarticlebreakdown',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 12, 30, 21, 438403)),
        ),
        migrations.AlterField(
            model_name='summarysizebreakdown',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 12, 30, 21, 437717)),
        ),
    ]
