# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0025_auto_20170923_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingtrend',
            name='publish_count',
        ),
    ]
