# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0026_remove_listingtrend_publish_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegionSummary',
        ),
        migrations.DeleteModel(
            name='SummaryLanguageBreakdown',
        ),
    ]
