# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0031_summarycapacitybreakdown'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListingTrend',
        ),
    ]
