# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0034_auto_20170926_1640'),
    ]

    operations = [
#        migrations.RemoveField(
#            model_name='prefecture',
#            name='prefecture_id',
#        ),
    ]
