# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0036_prefecture_prefecture_id'),
    ]

    operations = [
#        migrations.RenameField(
#            model_name='consumption',
#            old_name='prefecture_id',
#            new_name='prefecture',
#        ),
    ]
