# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0039_auto_20170926_1657'),
    ]

    operations = [
#        migrations.DeleteModel(
#            name='City',
#        ),
#        migrations.RemoveField(
#            model_name='foreignguest',
#            name='prefecture_id',
#        ),
#        migrations.RemoveField(
#            model_name='foreignguestm',
#            name='prefecture_id',
#        ),
#        migrations.RemoveField(
#            model_name='hoteltype',
#            name='prefecture',
#        ),
#        migrations.RemoveField(
#            model_name='prefecture',
#            name='prefecture_id',
#        ),
#        migrations.RemoveField(
#            model_name='priceofland',
#            name='prefecture_id',
#        ),
#        migrations.RemoveField(
#            model_name='regionsummary',
#            name='prefecture_id',
#        ),
#        migrations.RemoveField(
#            model_name='summaryarticlebreakdown',
#            name='region_summary_id',
#        ),
#        migrations.RemoveField(
#            model_name='summarycapacitybreakdown',
#            name='region_summary_id',
#        ),
#        migrations.RemoveField(
#            model_name='summarylanguagebreakdown',
#            name='region_summary_id',
#        ),
#        migrations.RemoveField(
#            model_name='summarysizebreakdown',
#            name='region_summary_id',
#        ),
#        migrations.RemoveField(
#            model_name='tourresource',
#            name='prefecture_id',
#        ),
#        migrations.RemoveField(
#            model_name='website',
#            name='prefecture_id',
#        ),
#        migrations.DeleteModel(
#            name='ForeignGuest',
#        ),
#        migrations.DeleteModel(
#            name='ForeignGuestM',
#        ),
#        migrations.DeleteModel(
#            name='HotelType',
#        ),
#        migrations.DeleteModel(
#            name='Prefecture',
#        ),
#        migrations.DeleteModel(
#            name='PriceofLand',
#        ),
#        migrations.DeleteModel(
#            name='Region',
#        ),
#        migrations.DeleteModel(
#            name='RegionSummary',
#        ),
#        migrations.DeleteModel(
#            name='SummaryArticleBreakdown',
#        ),
#        migrations.DeleteModel(
#            name='SummaryCapacityBreakdown',
#        ),
#        migrations.DeleteModel(
#            name='SummaryLanguageBreakdown',
#        ),
#        migrations.DeleteModel(
#            name='SummarySizeBreakdown',
#        ),
#        migrations.DeleteModel(
#            name='TourResource',
#        ),
#        migrations.DeleteModel(
#            name='WebSite',
#        ),
    ]
