# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0042_delete_consumption'),
    ]

    operations = [
#        migrations.CreateModel(
#            name='Consumption',
#            fields=[
#                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                ('csm_id', models.IntegerField(default=0)),
#                ('prefecture_id', models.IntegerField(default=0)),
#                ('num_of_answers', models.IntegerField(default=0, null=True)),
#                ('consumption', models.IntegerField(default=0, null=True)),
#            ],
#        ),
    ]
