# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0047_consumption_prefecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumption',
            name='prefecture',
        ),
        migrations.AddField(
            model_name='consumption',
            name='prefecture_id',
            field=models.IntegerField(default=0),
        ),
    ]
