# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0052_auto_20170926_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='city_id',
            new_name='city_id_web',
        ),
    ]
