# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0058_consumption_prefecture_id_csm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='prefecture_id_csm',
            field=models.ForeignKey(blank=True, db_column=b'prefecture_id_csm', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefecture_id_csm', to='ac_site.Region', to_field=b'prefecture_id'),
        ),
    ]
