# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 04:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0059_auto_20170927_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoteltype',
            name='prefecture_id_htl',
        ),
        migrations.RemoveField(
            model_name='regionsummary',
            name='region_summary_id',
        ),
        migrations.AddField(
            model_name='hoteltype',
            name='prefecture_htl',
            field=models.ForeignKey(blank=True, db_column=b'prefecture_id_htl', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefecture_id_htl', to='ac_site.Region', to_field=b'prefecture_id'),
        ),
        migrations.AlterField(
            model_name='foreignguest',
            name='prefecture_id_frg',
            field=models.ForeignKey(blank=True, db_column=b'prefecture_id_frg', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefecture_id_frg', to='ac_site.Region', to_field=b'prefecture_id'),
        ),
        migrations.AlterField(
            model_name='foreignguestm',
            name='prefecture_id_frgm',
            field=models.ForeignKey(blank=True, db_column=b'prefecture_id_frgm', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefecture_id_frgm', to='ac_site.Region', to_field=b'prefecture_id'),
        ),
        migrations.AlterField(
            model_name='prefecture',
            name='prefecture_id_pref',
            field=models.ForeignKey(blank=True, db_column=b'prefecture_id_pref', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefecture_id_pref', to='ac_site.Region', to_field=b'prefecture_id'),
        ),
        migrations.AlterField(
            model_name='priceofland',
            name='prefecture_id_pol',
            field=models.ForeignKey(blank=True, db_column=b'prefecture_id_pol', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefecture_id_pol', to='ac_site.Region', to_field=b'prefecture_id'),
        ),
        migrations.AlterField(
            model_name='regionsummary',
            name='prefecture_id_rgs',
            field=models.ForeignKey(blank=True, db_column=b'prefecture_id_rgs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefecture_id_rgs', to='ac_site.Region', to_field=b'prefecture_id'),
        ),
        migrations.AlterField(
            model_name='summaryarticlebreakdown',
            name='region_summary_id_artcl',
            field=models.ForeignKey(blank=True, db_column=b'region_summary_id_artcl', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_summary_id_artcl', to='ac_site.RegionSummary', to_field=b'region_id'),
        ),
        migrations.AlterField(
            model_name='summarycapacitybreakdown',
            name='region_summary_id_cap',
            field=models.ForeignKey(blank=True, db_column=b'region_summary_id_cap', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_summary_id_cap', to='ac_site.RegionSummary', to_field=b'region_id'),
        ),
        migrations.AlterField(
            model_name='summarylanguagebreakdown',
            name='region_summary_id_lang',
            field=models.ForeignKey(blank=True, db_column=b'region_summary_id_lang', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_summary_id_lang', to='ac_site.RegionSummary', to_field=b'region_id'),
        ),
        migrations.AlterField(
            model_name='summarysizebreakdown',
            name='region_summary_id_size',
            field=models.ForeignKey(blank=True, db_column=b'region_summary_id_size', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_summary_id_size', to='ac_site.RegionSummary', to_field=b'region_id'),
        ),
        migrations.AlterField(
            model_name='tourresource',
            name='prefecture_id_scr',
            field=models.ForeignKey(blank=True, db_column=b'prefecture_id_scr', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefecture_id_scr', to='ac_site.Region', to_field=b'prefecture_id'),
        ),
        migrations.AlterField(
            model_name='website',
            name='prefecture_id_web',
            field=models.ForeignKey(blank=True, db_column=b'prefecture_id_web', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefecture_id_web', to='ac_site.Region', to_field=b'prefecture_id'),
        ),
    ]
