# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0065_auto_20170927_1911'),
    ]

    operations = [
#        migrations.AlterField(
#            model_name='prefecture',
#            name='prefecture',
#            field=models.OneToOneField(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pref_name', to='ac_site.Region'),
#        ),
    ]
