# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0071_auto_20170928_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefecture',
            name='pref_id_cosumption',
            field=models.ForeignKey(blank=True, db_column=b'pref_id_consumption', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pref_id_consumption', to='ac_site.Consumption', to_field=b'prefecture_id_csm'),
        ),
        migrations.AddField(
            model_name='prefecture',
            name='pref_id_hoteltype',
            field=models.ForeignKey(blank=True, db_column=b'pref_id_hoteltype', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pref_id_hoteltype', to='ac_site.HotelType', to_field=b'prefecture_id_htl'),
        ),
        migrations.AddField(
            model_name='prefecture',
            name='pref_id_website',
            field=models.ForeignKey(blank=True, db_column=b'pref_id_website', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pref_id_website', to='ac_site.WebSite', to_field=b'prefecture_id_web'),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='prefecture_id_csm',
            field=models.OneToOneField(blank=True, db_column=b'prefecture_id_csm', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefecture_id_csm', to='ac_site.Prefecture', to_field=b'prefecture_id_pref'),
        ),
        migrations.AlterField(
            model_name='hoteltype',
            name='prefecture_id_htl',
            field=models.OneToOneField(blank=True, db_column=b'prefecture_id_htl', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefecture_id_htl', to='ac_site.Prefecture', to_field=b'prefecture_id_pref'),
        ),
        migrations.AlterField(
            model_name='website',
            name='prefecture_id_web',
            field=models.OneToOneField(blank=True, db_column=b'prefecture_id_web', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefecture_id_web', to='ac_site.Prefecture', to_field=b'prefecture_id_pref'),
        ),
    ]
