# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0076_auto_20170928_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summaryarticlebreakdown',
            old_name='region_summary_id_artcl',
            new_name='region_summary',
        ),
        migrations.RenameField(
            model_name='summarycapacitybreakdown',
            old_name='region_summary_id_cap',
            new_name='region_summary',
        ),
        migrations.RenameField(
            model_name='summarylanguagebreakdown',
            old_name='region_summary_id_lang',
            new_name='region_summary',
        ),
        migrations.RenameField(
            model_name='summarysizebreakdown',
            old_name='region_summary_id_size',
            new_name='region_summary',
        ),
    ]
