# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0078_auto_20170928_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='prefecture_id',
            new_name='link_prefecture',
        ),
    ]
