# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0081_auto_20170928_1618'),
    ]

    operations = [
#        migrations.DeleteModel(
#            name='City',
#        ),
#        migrations.RemoveField(
#            model_name='prefecture',
#            name='consumption_id',
#        ),
#        migrations.RemoveField(
#            model_name='prefecture',
#            name='hoteltype_id',
#        ),
#        migrations.RemoveField(
#            model_name='prefecture',
#            name='website_id',
#        ),#        migrations.RemoveField(
#            model_name='consumption',
#            name='prefecture_id_csm',
#        ),
#        migrations.RemoveField(
#            model_name='foreignguest',
#            name='prefecture_id_frg',
#        ),
#        migrations.RemoveField(
#            model_name='foreignguestm',
#            name='prefecture_id_frgm',
#        ),
#        migrations.RemoveField(
#            model_name='hoteltype',
#            name='prefecture_id_htl',
#        ),
#        migrations.RemoveField(
#            model_name='prefecture',
#            name='pref_id_consumption',
#        ),
#        migrations.RemoveField(
#            model_name='prefecture',
#            name='pref_id_hoteltype',
#        ),
#        migrations.RemoveField(
#            model_name='prefecture',
#            name='pref_id_website',
#        ),
#        migrations.RemoveField(
#            model_name='priceofland',
#            name='prefecture_id_pol',
#        ),
#        migrations.RemoveField(
#            model_name='region',
#            name='link_prefecture',
#        ),
#        migrations.RemoveField(
#            model_name='regionsummary',
#            name='prefecture_id_rgs',
#        ),
#        migrations.RemoveField(
#            model_name='summaryarticlebreakdown',
#            name='region_summary',
#        ),
#        migrations.RemoveField(
#            model_name='summarycapacitybreakdown',
#            name='region_summary',
#        ),
#        migrations.RemoveField(
#            model_name='summarylanguagebreakdown',
#            name='region_summary',
#        ),
#        migrations.RemoveField(
#            model_name='summarysizebreakdown',
#            name='region_summary',
#        ),
#        migrations.RemoveField(
#            model_name='tourresource',
#            name='prefecture_id_scr',
#        ),
#        migrations.RemoveField(
#            model_name='website',
#            name='prefecture_id_web',
#        ),
#        migrations.DeleteModel(
#            name='Consumption',
#        ),
#        migrations.DeleteModel(
#            name='ForeignGuest',
#        ),
#        migrations.DeleteModel(
#            name='ForeignGuestM',
#        ),
#        migrations.DeleteModel(
#            name='HotelType',
#        ),
#        migrations.DeleteModel(
#            name='Prefecture',
#        ),
#        migrations.DeleteModel(
#            name='PriceofLand',
#        ),
#        migrations.DeleteModel(
#            name='Region',
#        ),
#        migrations.DeleteModel(
#            name='RegionSummary',
#        ),
#        migrations.DeleteModel(
#            name='SummaryArticleBreakdown',
#        ),
#        migrations.DeleteModel(
#            name='SummaryCapacityBreakdown',
#        ),
#        migrations.DeleteModel(
#            name='SummaryLanguageBreakdown',
#        ),
#        migrations.DeleteModel(
#            name='SummarySizeBreakdown',
#        ),
#        migrations.DeleteModel(
#            name='TourResource',
#        ),
#        migrations.DeleteModel(
#            name='WebSite',
#        ),
    ]
