# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0082_auto_20170928_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField(default=0)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csm_id', models.IntegerField(default=0)),
                ('num_of_answers', models.IntegerField(default=0, null=True)),
                ('consumption', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForeignGuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_foreign_id', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('number_of_guest', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForeignGuestM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_foreign_month_id', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('number_of_guest', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.IntegerField(default=0)),
                ('hotel', models.IntegerField(default=0, null=True)),
                ('ryokan', models.IntegerField(default=0, null=True)),
                ('condominium', models.IntegerField(default=0, null=True)),
                ('dorm', models.IntegerField(default=0, null=True)),
                ('house', models.IntegerField(default=0, null=True)),
                ('youth_hostel', models.IntegerField(default=0, null=True)),
                ('other', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture_id', models.IntegerField(default=0, unique=True)),
                ('prefecture', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PriceofLand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceofland_id', models.IntegerField(default=0)),
                ('link_city', models.IntegerField(default=0, null=True)),
                ('properties', models.IntegerField(default=0, null=True)),
                ('average_price', models.IntegerField(default=0, null=True)),
                ('upper_price', models.IntegerField(default=0, null=True)),
                ('lower_price', models.IntegerField(default=0, null=True)),
                ('link_prefecture', models.ForeignKey(blank=True, db_column=b'link_prefecture_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_priceofland', to='ac_site.Prefecture', to_field=b'prefecture_id')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_city', models.IntegerField(default=0, unique=True)),
                ('link_prefecture', models.OneToOneField(blank=True, db_column=b'link_prefecture_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_region', to='ac_site.Prefecture', to_field=b'prefecture_id')),
            ],
        ),
        migrations.CreateModel(
            name='RegionSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_id', models.IntegerField(default=0, unique=True)),
                ('link_city', models.IntegerField(default=0, null=True)),
                ('total_listing', models.IntegerField(default=0, null=True)),
                ('publish_count', models.IntegerField(default=0, null=True)),
                ('suspend_count', models.IntegerField(default=0, null=True)),
                ('reviewed_count', models.IntegerField(default=0, null=True)),
                ('non_reviewed_count', models.IntegerField(default=0, null=True)),
                ('average_price', models.IntegerField(default=0, null=True)),
                ('monthly_sales', models.IntegerField(default=0, null=True)),
                ('link_prefecture', models.ForeignKey(blank=True, db_column=b'link_prefecture_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_regionsummary', to='ac_site.Prefecture', to_field=b'prefecture_id')),
            ],
        ),
        migrations.CreateModel(
            name='SummaryArticleBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_type', models.CharField(max_length=10, null=True)),
                ('listing_count', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('region_summary', models.ForeignKey(blank=True, db_column=b'region_summary_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_breakdown', to='ac_site.RegionSummary', to_field=b'region_id')),
            ],
        ),
        migrations.CreateModel(
            name='SummaryCapacityBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity_type', models.CharField(max_length=10, null=True)),
                ('listing_count', models.IntegerField(default=0, null=True)),
                ('average_sales', models.IntegerField(default=0, null=True)),
                ('average_rental_fee', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('region_summary', models.ForeignKey(blank=True, db_column=b'region_summary_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capacity_breakdown', to='ac_site.RegionSummary', to_field=b'region_id')),
            ],
        ),
        migrations.CreateModel(
            name='SummaryLanguageBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_type', models.CharField(max_length=10, null=True)),
                ('listing_count', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('region_summary', models.ForeignKey(blank=True, db_column=b'region_summary_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language_breakdown', to='ac_site.RegionSummary', to_field=b'region_id')),
            ],
        ),
        migrations.CreateModel(
            name='SummarySizeBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_size', models.CharField(max_length=10, null=True)),
                ('listing_count', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('region_summary', models.ForeignKey(blank=True, db_column=b'region_summary_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_breakdown', to='ac_site.RegionSummary', to_field=b'region_id')),
            ],
        ),
        migrations.CreateModel(
            name='TourResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scr_id', models.IntegerField(default=0)),
                ('link_city', models.IntegerField(default=0, null=True)),
                ('scr_type1', models.CharField(max_length=20, null=True)),
                ('scr_type2', models.CharField(max_length=20, null=True)),
                ('scr_name', models.CharField(max_length=50, null=True)),
                ('scr_rank', models.CharField(max_length=5, null=True)),
                ('scr_score', models.IntegerField(default=0, null=True)),
                ('link_prefecture', models.ForeignKey(blank=True, db_column=b'link_prefecture_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_tourresource', to='ac_site.Prefecture', to_field=b'prefecture_id')),
            ],
        ),
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_id', models.IntegerField(default=0)),
                ('link_city', models.IntegerField(default=0, null=True)),
                ('website', models.IntegerField(default=0, null=True)),
                ('link_prefecture', models.OneToOneField(blank=True, db_column=b'link_prefecture_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_website', to='ac_site.Prefecture', to_field=b'prefecture_id')),
            ],
        ),
        migrations.AddField(
            model_name='hoteltype',
            name='link_prefecture',
            field=models.OneToOneField(blank=True, db_column=b'link_prefecture_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_hoteltype', to='ac_site.Prefecture', to_field=b'prefecture_id'),
        ),
        migrations.AddField(
            model_name='foreignguestm',
            name='link_prefecture',
            field=models.ForeignKey(blank=True, db_column=b'link_prefecture_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_foreignguestm', to='ac_site.Prefecture', to_field=b'prefecture_id'),
        ),
        migrations.AddField(
            model_name='foreignguest',
            name='link_prefecture',
            field=models.ForeignKey(blank=True, db_column=b'link_prefecture_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_foreignguest', to='ac_site.Prefecture', to_field=b'prefecture_id'),
        ),
        migrations.AddField(
            model_name='consumption',
            name='link_prefecture',
            field=models.OneToOneField(blank=True, db_column=b'link_prefecture_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_consumption', to='ac_site.Prefecture', to_field=b'prefecture_id'),
        ),
    ]
