# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0088_regionsummary_summaryarticlebreakdown_summarycapacitybreakdown_summarylanguagebreakdown_summarysizeb'),
    ]

    operations = [
#        migrations.RemoveField(
#            model_name='region',
#            name='prefecture_id',
#        ),
#        migrations.AddField(
#            model_name='region',
#            name='prefecture',
#            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_region', to='ac_site.Prefecture'),
#        ),
    ]
