# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0089_auto_20171001_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualsummary',
            name='region',
        ),
        migrations.RemoveField(
            model_name='city',
            name='region',
        ),
        migrations.RemoveField(
            model_name='foreignguestcount',
            name='region',
        ),
        migrations.RemoveField(
            model_name='prefecture',
            name='region',
        ),
        migrations.RemoveField(
            model_name='priceofland',
            name='region',
        ),
        migrations.RemoveField(
            model_name='regionsummary',
            name='region',
        ),
        migrations.RemoveField(
            model_name='summaryarticlebreakdown',
            name='region_summary',
        ),
        migrations.RemoveField(
            model_name='summarycapacitybreakdown',
            name='region_summary',
        ),
        migrations.RemoveField(
            model_name='summarylanguagebreakdown',
            name='region_summary',
        ),
        migrations.RemoveField(
            model_name='summarysizebreakdown',
            name='region_summary',
        ),
        migrations.RemoveField(
            model_name='tourresource',
            name='region',
        ),
        migrations.DeleteModel(
            name='AnnualSummary',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='ForeignGuestCount',
        ),
        migrations.DeleteModel(
            name='Prefecture',
        ),
        migrations.DeleteModel(
            name='PriceofLand',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='RegionSummary',
        ),
        migrations.DeleteModel(
            name='SummaryArticleBreakdown',
        ),
        migrations.DeleteModel(
            name='SummaryCapacityBreakdown',
        ),
        migrations.DeleteModel(
            name='SummaryLanguageBreakdown',
        ),
        migrations.DeleteModel(
            name='SummarySizeBreakdown',
        ),
        migrations.DeleteModel(
            name='TourResource',
        ),
    ]
