# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0092_auto_20171001_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualsummary',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_annualsummary', to='ac_site.Region'),
        ),
        migrations.AddField(
            model_name='foreignguestcount',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_foreignguestcount', to='ac_site.Region'),
        ),
        migrations.AddField(
            model_name='regionsummary',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_regionsummary', to='ac_site.Region'),
        ),
    ]
