# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0095_auto_20171001_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture_code', models.IntegerField(default=0)),
                ('city_code', models.IntegerField(default=0, null=True)),
                ('year', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('rent', models.IntegerField(default=0)),
                ('restroom_facility_cost', models.IntegerField(default=0)),
                ('bathroom_facility_cost', models.IntegerField(default=0)),
                ('kitchen_facility_cost', models.IntegerField(default=0)),
                ('reform_fee', models.IntegerField(default=0)),
                ('repainting_fee', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_cost', to='ac_site.Region')),
            ],
        ),
#        migrations.CreateModel(
#            name='GuestNationality',
#            fields=[
#                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                ('prefecture_code', models.IntegerField(default=0)),
#                ('answer_count', models.IntegerField(default=0)),
#                ('visit_duration', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
#                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
#            ],
#        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality_code', models.IntegerField(default=0)),
                ('nationality_name', models.CharField(max_length=30)),
            ],
        ),
#        migrations.AddField(
#            model_name='guestnationality',
#            name='nationality_code',
#            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_guestnationality_nationality', to='ac_site.Nationality'),
#        ),
#        migrations.AddField(
#            model_name='guestnationality',
#            name='region',
#            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_guestnationality', to='ac_site.Region'),
#        ),
    ]
