# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0097_guestnationality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_listing_rank', models.IntegerField(default=0)),
                ('average_price_rank', models.IntegerField(default=0)),
                ('monthly_sales_rank', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_ranking', to='ac_site.Region')),
            ],
        ),
    ]
