# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_site', '0098_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='city_code',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ranking',
            name='prefecture_code',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
